/* Automatically generated by './build/bin/build-entry.js' */
import "./scss/index.scss"
import Alert from './alert/index.js';


const components = [
  Alert
];

const install = function(Vue, opts = {}) {
  components.forEach(component => {
    Vue.component(component.name, component);
  });

};

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}

export default {
  version: '0.0.1',
  Alert,
  install
};
